name: Déploiement FTP Genelife2

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Déploiement FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: './src/'
          server-dir: '/'
          delete: false
